# Used to change the functions associated with each button

button_A:                        ### Button associated with the command
  command_name: 'Homing'
  command: 'H_0'                 # Code of the command

button_B:
  command_name: 'Calibration'
  command: 'C_0'

button_C:
  command_name: 'Watering'
  command: 'P_4'

