# Used to change the functions associated with each button.

button_a:                        ### Button associated with the command
  command_name: 'Homing'
  command: 'H_0'                 # Code of the command

button_b:
  command_name: 'Calibration'
  command: 'C_0'

button_c:
  command_name: 'Watering'
  command: 'P_4'                  # TODO: Not yet fully implemented
