# Contains all commands and their possible end responses

long_term:
  G00: 
    responses: ['R02', 'R03']
  G01: 
    responses: ['R02', 'R03']
  G28: 
    responses: ['R02', 'R03']
  F11:
    responses: ['R02', 'R03']
  F12: 
    responses: ['R02', 'R03']
  F13: 
    responses: ['R02', 'R03']

calibration:
  F14: 
    responses: ['R02', 'R03']
  F15: 
    responses: ['R02', 'R03']
  F16: 
    responses: ['R02', 'R03']

blocking:
  F20: 
    responses: ['R02', 'R03']
  F44: 
    responses: ['R02', 'R03']
  F21: 
    responses: ['R21']
  F42: 
    responses: ['R41']

# Priority commands
priority:
  F09: 
    responses: ['R02', 'R03']
  E: 
    responses: ['R87']

