# File used as an enum to store all the constants
# related to the farmbot panel, including button pins,
# LED pins and LED states

# Button Pins
button_estop: 16
button_unlock: 22
button_A: 26
button_B: 5
button_C: 20

# Button LEDs
estop_led: 17
unlock_led: 23
button_led_A: 27
button_led_B: 6
button_led_C: 21

# Standard LEDs
led_1: 24
led_2: 25
led_3: 12
led_4: 13

# LED states
led_on: 1
led_off: 0
led_flashing: 2