# Used to change the autonomous commands

#'time' :
#   command : 'command to execute at this time'

Task 1  :
  time : '11:07'
  command : 'P_4'    

Task 2  :
  time : '12:00'
  command : 'H_0'       
