# Message used as an enum to store all the constants
# related to the farmbot panel, including button pins,
# LED pins and LED states

# Button Pins
uint8 BUTTON_ESTOP = 16
uint8 BUTTON_UNLOCK = 22
uint8 BUTTON_A = 26
uint8 BUTTON_B = 5
uint8 BUTTON_C = 20

# Button LEDs
uint8 ESTOP_LED = 17
uint8 UNLOCK_LED = 23
uint8 BUTTON_LED_A = 27
uint8 BUTTON_LED_B = 6
uint8 BUTTON_LED_C = 21

# Standard LEDs
uint8 LED1 = 24
uint8 LED2 = 25
uint8 LED3 = 12
uint8 LED4 = 13

# LED states
uint8 ON = 1
uint8 OFF = 0
uint8 FLASHING = 2