camera_constants:
  DEPTH_MIN_VAL: 180  # Minimum depth value in mm
  DEPTH_MAX_VAL: 1000  # Maximum depth value in mm
  FOCAL_LENGTH_PX: 462  # Focal length in pixels (832/720)*400 (would be 832 at 720p, but we want 400p because that gives shorter standoff than 800)
  BASELINE: 75  # Baseline distance in mm
camera_calibration:
  CAM_ROTATION: 0
  SCALE: 1
  CAMERA_Z: 0
  CAMERA_X: 0
  CAMERA_Y: 0
  CENTER_PIXEL_X: 200
  CENTER_PIXEL_Y: 200