# Used to change the functions associated with each button 

button_A:            ### Button associated with the command
  command_name : 'ESTOP'
  command : 'E'              # Code of the command
  command_type: 'LOW_LEVEL'        # command type : LOW_LEVEL or HIGH_LEVEL

button_B:         
  command_name : 'Calibration'   
  command : 'C_0'             
  command_type: 'HIGH_LEVEL' 

button_C:            
  command_name : 'Watering'
  command : 'P_4'             
  command_type: 'HIGH_LEVEL' 

