PARAM_CONFIG_OK: [2, 0]              # Parameter: [id, value]
PARAM_USE_EEPROM: [3, 0]
PARAM_E_STOP_ON_MOV_ERR: [4, 0]
PARAM_MOV_NR_RETRY: [5, 0]
MOVEMENT_TIMEOUT_X: [11, 0]
MOVEMENT_TIMEOUT_Y: [12, 0]
MOVEMENT_TIMEOUT_Z: [13, 0]
MOVEMENT_KEEP_ACTIVE_X: [15, 0]
MOVEMENT_KEEP_ACTIVE_Y: [16, 0]
MOVEMENT_KEEP_ACTIVE_Z: [17, 0]
MOVEMENT_HOME_AT_BOOT_X: [18, 0]
MOVEMENT_HOME_AT_BOOT_Y: [19, 0]
MOVEMENT_HOME_AT_BOOT_Z: [20, 0]
MOVEMENT_INVERT_ENDPOINTS_X: [21, 0]
MOVEMENT_INVERT_ENDPOINTS_Y: [22, 0]
MOVEMENT_INVERT_ENDPOINTS_Z: [23, 0]
MOVEMENT_ENABLE_ENDPOINTS_X: [25, 0]
MOVEMENT_ENABLE_ENDPOINTS_Y: [26, 0]
MOVEMENT_ENABLE_ENDPOINTS_Z: [27, 0]
MOVEMENT_INVERT_MOTOR_X: [31, 0]
MOVEMENT_INVERT_MOTOR_Y: [32, 0]
MOVEMENT_INVERT_MOTOR_Z: [33, 0]
MOVEMENT_SECONDARY_MOTOR_X: [36, 0]
MOVEMENT_SECONDARY_MOTOR_INVERT_X: [37, 0]
MOVEMENT_STEPS_ACC_DEC_X: [41, 0]
MOVEMENT_STEPS_ACC_DEC_Y: [42, 0]
MOVEMENT_STEPS_ACC_DEC_Z: [43, 0]
MOVEMENT_STEPS_ACC_DEC_Z2: [44, 0]
MOVEMENT_STOP_AT_HOME_X: [45, 0]
MOVEMENT_STOP_AT_HOME_Y: [46, 0]
MOVEMENT_STOP_AT_HOME_Z: [47, 0]
MOVEMENT_HOME_UP_X: [51, 0]
MOVEMENT_HOME_UP_Y: [52, 0]
MOVEMENT_HOME_UP_Z: [53, 0]
MOVEMENT_STEP_PER_MM_X: [55, 0]
MOVEMENT_STEP_PER_MM_Y: [56, 0]
MOVEMENT_STEP_PER_MM_Z: [57, 0]
MOVEMENT_MIN_SPD_X: [61, 0]
MOVEMENT_MIN_SPD_Y: [62, 0]
MOVEMENT_MIN_SPD_Z: [63, 0]
MOVEMENT_MIN_SPD_Z2: [64, 0]
MOVEMENT_HOME_SPD_X: [65, 0]
MOVEMENT_HOME_SPD_Y: [66, 0]
MOVEMENT_HOME_SPD_Z: [67, 0]
MOVEMENT_MAX_SPD_X: [71, 0]
MOVEMENT_MAX_SPD_Y: [72, 0]
MOVEMENT_MAX_SPD_Z: [73, 0]
MOVEMENT_MAX_SPD_Z2: [74, 0]
MOVEMENT_INVERT_2_ENDPOINTS_X: [75, 0]
MOVEMENT_INVERT_2_ENDPOINTS_Y: [76, 0]
MOVEMENT_INVERT_2_ENDPOINTS_Z: [77, 0]
MOVEMENT_MOTOR_CURRENT_X: [81, 0]
MOVEMENT_MOTOR_CURRENT_Y: [82, 0]
MOVEMENT_MOTOR_CURRENT_Z: [83, 0]
MOVEMENT_STALL_SENSITIVITY_X: [85, 0]
MOVEMENT_STALL_SENSITIVITY_Y: [86, 0]
MOVEMENT_STALL_SENSITIVITY_Z: [87, 0]
MOVEMENT_MICROSTEPS_X: [91, 0]
MOVEMENT_MICROSTEPS_Y: [92, 0]
MOVEMENT_MICROSTEPS_Z: [93, 0]
ENCODER_ENABLED_X: [101, 0]
ENCODER_ENABLED_Y: [102, 0]
ENCODER_ENABLED_Z: [103, 0]
ENCODER_TYPE_X: [105, 0]
ENCODER_TYPE_Y: [106, 0]
ENCODER_TYPE_Z: [107, 0]
ENCODER_MISSED_STEPS_MAX_X: [111, 0]
ENCODER_MISSED_STEPS_MAX_Y: [112, 0]
ENCODER_MISSED_STEPS_MAX_Z: [113, 0]
ENCODER_SCALING_X: [115, 0]
ENCODER_SCALING_Y: [116, 0]
ENCODER_SCALING_Z: [117, 0]
ENCODER_MISSED_STEPS_DECAY_X: [121, 0]
ENCODER_MISSED_STEPS_DECAY_Y: [122, 0]
ENCODER_MISSED_STEPS_DECAY_Z: [123, 0]
ENCODER_USE_FOR_POS_X: [125, 0]
ENCODER_USE_FOR_POS_Y: [126, 0]
ENCODER_USE_FOR_POS_Z: [127, 0]
ENCODER_INVERT_X: [131, 0]
ENCODER_INVERT_Y: [132, 0]
ENCODER_INVERT_Z: [133, 0]
MOVEMENT_AXIS_NR_STEPS_X: [141, 0]
MOVEMENT_AXIS_NR_STEPS_Y: [142, 0]
MOVEMENT_AXIS_NR_STEPS_Z: [143, 0]
MOVEMENT_STOP_AT_MAX_X: [145, 0]
MOVEMENT_STOP_AT_MAX_Y: [146, 0]
MOVEMENT_STOP_AT_MAX_Z: [147, 0]
MOVEMENT_CALIBRATION_RETRY_X: [161, 0]
MOVEMENT_CALIBRATION_RETRY_Y: [162, 0]
MOVEMENT_CALIBRATION_RETRY_Z: [163, 0]
MOVEMENT_AXIS_STEALTH_X: [165, 0]
MOVEMENT_AXIS_STEALTH_Y: [166, 0]
MOVEMENT_AXIS_STEALTH_Z: [167, 0]
MOVEMENT_CALIBRATION_DEADZONE_X: [171, 0]
MOVEMENT_CALIBRATION_DEADZONE_Y: [172, 0]
MOVEMENT_CALIBRATION_DEADZONE_Z: [173, 0]
MOVEMENT_CALIBRATION_RETRY_TOTAL_X: [175, 0]
MOVEMENT_CALIBRATION_RETRY_TOTAL_Y: [176, 0]
MOVEMENT_CALIBRATION_RETRY_TOTAL_Z: [177, 0]
PIN_REPORT_1_PIN_NR: [198, 0]
PIN_REPORT_2_PIN_NR: [199, 0]
PIN_GUARD_1_PIN_NR: [201, 0]
PIN_GUARD_1_TIME_OUT: [202, 0]
PIN_GUARD_1_ACTIVE_STATE: [203, 0]
PIN_GUARD_2_PIN_NR: [205, 0]
PIN_GUARD_2_TIME_OUT: [206, 0]
PIN_GUARD_2_ACTIVE_STATE: [207, 0]
PIN_GUARD_3_PIN_NR: [211, 0]
PIN_GUARD_3_TIME_OUT: [212, 0]
PIN_GUARD_3_ACTIVE_STATE: [213, 0]
PIN_GUARD_4_PIN_NR: [215, 0]
PIN_GUARD_4_TIME_OUT: [216, 0]
PIN_GUARD_4_ACTIVE_STATE: [217, 0]
PIN_GUARD_5_PIN_NR: [221, 0]
PIN_GUARD_5_TIME_OUT: [222, 0]
PIN_GUARD_5_ACTIVE_STATE: [223, 0]